### ISSUE TITLE
Undefined offset: 1 scout-extended with extended & Record too big

### ISSUE THREAD

**Issue by icemancast** [algolia/scout-extended#113]
I keep getting an undefined offset: 1 with scout extended at this line:
https://github.com/algolia/scout-extended/blob/master/src/Searchable/ObjectIdEncrypter.php#L77

Maybe due to Algolia search client incompatibility if you see here: 
https://github.com/laravel/scout/issues/328

**Comment by nunomaduro** [comment]
@icemancast Have you re-imported your data after installing Scout Extended? If not, you must perform a `scout-reimport`.

**Comment by nunomaduro** [comment]
Just added a warning on the code itself, to help the developer next time this happens: https://github.com/algolia/scout-extended/commit/3048d74302c4e8e5bf8a02310a72d939b2c2a15b

**Comment by icemancast** [comment]
@nunomaduro no I did not. I'll try again here and post back. Is there an incompatibility with the algoliasearch-client-php client required by scout-extended and laravel/scout? Their docs force 1.27 install.

**Comment by nunomaduro** [comment]
@icemancast Laravel Scout uses Algolia PHP Client V1. Scout Extended uses Algolia PHP Client v2.  👍

**Comment by icemancast** [comment]
@nunomaduro ended getting a Record at the position 40 objectID=App\Customer::41 is too big size=103328 bytes

so reimport failed. To get around this before i uploaded my records csv to dashboard. If there is a better way let me know.

**Comment by nunomaduro** [comment]
@icemancast No horries, I am here to help you. Let's discuss this issue here instead of the private support. Other people may have the same issue.

With Scout Extended, you should not import thing using the dashboard. You should import your data using `scout:import` or `scout:reimport`.

**Problem**: Seems that the record create by the customer 41 it's to big for Algolia.

**Solution**: Debug the code using the `toSearchableArray` method to find out what is making your record to big. Probably a TEXT field, or similar. And then:

1. Truncate the field value using the `toSearchableArray`: https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-searchable-data/?language=php#customize-records.

2. Split the value using Scout Extended's Splitters: https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/split-large-records.

**Comment by icemancast** [comment]
Thanks @nunomaduro will try there here and report back.

**Comment by nunomaduro** [comment]
Yes. You just have to implement the method `toSearchableArray` on the searchable model: 

```php
    public function toSearchableArray()
    {
        // The array variable should contain ONLY information that you want to be searchable.
        $array = [
            'id' => $this->id,
            'name' => $this->name,
            'address' => $this->address,
            ... // more information
        ];

        return $this->transform($array);
    }
```

Then, if you run `scout:reimport` everything should be good.

More info: https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-searchable-data/?language=php#customize-records.

**Comment by icemancast** [comment]
@nunomaduro thank you that did the trick. That model had many relationships making it bigger. Thanks!

**Comment by nunomaduro** [comment]
Super happy that everything it's good for you now!

Please if you have more questions fell free to ask them.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
