### ISSUE TITLE
Record at the position 0 objectID=App\Article::16 is too big size=13406 bytes. Contact us if you need an extended quota

### ISSUE THREAD

**Issue by MasterMindLegion** [algolia/scout-extended#242]
Hello guys, 

I have installed scout-extended , but still, there is an issue regarding to index article with big size. It is an long article, which I would like to indices, how to proceed please?

I had normal scout installed -> than I found out err _**_Record at the position 0 objectID=App\Article::16 is too big size=13406 bytes. Contact us if you need an extended quota_**_ -> I have installed scout extended, I flushed all models indecis and tried to save an article once more.

**Comment by DevinCodes** [comment]
For most Algolia plans, the Algolia engine only accepts records that are 10kb max. If records are too big, the engine will reject it with the error message you're seeing here.

There's public documentation on [how to reduce the size of records](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/reducing-object-size/), as well as documentation on indexing [long documents](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/).

I'm closing this issue since it's related to the Algolia engine, and not Scout Extended. If there's still issues after you've reduced the record size, please reach out to Algolia support 🙂 

Cheers!
