### ISSUE TITLE
Add scope for search

### ISSUE THREAD

**Issue by kossa** [algolia/scout-extended#270]
- Laravel version: 8.31
- Algolia Scout Extended version: v1.13.0
- Algolia Client Version: #.#.#
- Language Version: php7.4

### Description
I want to add some filters, like price between ..., there is a way to add scope ? so dont need to duplicate the same code ?

**Comment by DevinCodes** [comment]
Hi @kossa ,

Unfortunately, this is not possible for us to do. Since records in Algolia are not relational, there's only support for [simple where clause](https://laravel.com/docs/8.x/scout#where-clauses), which you have to define manually. Scout Extended adds [some extra `where*` methods](https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?client=php) (such as `whereBetween`), but unfortunately we're not able to apply scopes.

**Comment by kossa** [comment]
Thank you @DevinCodes
