### ISSUE TITLE
Should allow to change full objectId

### ISSUE THREAD

**Issue by osama-klabs** [algolia/scout-extended#293]
- Laravel version: 8
- Algolia Scout Extended version: 1.20
- Algolia Client Version: 3.1
- Language Version: 7.4

### Description
I am trying to change objectId from App\Models\{anyModel}::{id} to id{id}
Below function only change the key not whole objectId (model name)
```
public function getScoutKey()
    {
        return $this->id;
    }
```

### Steps To Reproduce
Just run import command you will see the objectId in terminal

**Comment by DevinCodes** [comment]
Hi @osama-klabs ,

Unfortunately, it's not possible to do this. The logic that generates this key lives in the `final` class `ObjectIdEncrypter`. Since this is a `final` class, it's not possible to override any methods on it.

May I ask why you need to update the objectID format exactly? Perhaps we can find a way around that requirement.

**Comment by osama-klabs** [comment]
I have multiple projects with different model namespace like App\Models\Product, App\Product etc and they are using same database as well as algolia account
